name: flutter_weather_demo
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2
  flutter_command: any 
  get_it: ^5.0.0
  get_it_mixin:
    path: ../
  functional_listener: any
  firebase_core: ^0.5.0+1
  firebase_auth: ^0.18.1+2

flutter:
  uses-material-design: true
